import plant from '../res/plant.svg';
import weed from '../res/weed.svg';

const plants = [
  {
    id: 1,
    image: plant,
    name: 'Monstera',
    type: 'Outdoor',
    time: '26 week',
    humidity: 19,
    fertilizer: 86,
    watering: 36,
    watertank: 10,
    light: 78,
    temperature: 24,
  },
  {
    id: 2,
    image: plant,
    name: 'Monstera',
    type: 'Indoor',
    time: '26 week',
    humidity: 70,
    fertilizer: 50,
    watering: 20,
    watertank: 90,
    light: 100,
    temperature: 25,
  },
  {
    id: 3,
    image: plant,
    name: 'Monstera',
    type: 'Outdoor',
    time: '26 week',
    humidity: 45,
    fertilizer: 66,
    watering: 69,
    watertank: 50,
    light: 60,
    temperature: 30,
  },
  {
    id: 4,
    image: plant,
    name: 'Calathea',
    type: 'Indoor',
    time: '26 week',
    humidity: 19,
    fertilizer: 86,
    watering: 36,
    watertank: 10,
    light: 78,
    temperature: 24,
  },
  {
    id: 5,
    image: weed,
    name: 'Gorilla G.',
    type: 'Indoor',
    time: '26 week',
    humidity: 19,
    fertilizer: 86,
    watering: 36,
    watertank: 4,
    light: 2,
    temperature: 0,
  },
  {
    id: 6,
    image: weed,
    name: 'Blueberry',
    type: 'Indoor',
    time: '420 week',
    humidity: 19,
    fertilizer: 86,
    watering: 36,
    watertank: 4,
    light: 2,
    temperature: 0,
  },
  {
    id: 7,
    image: weed,
    name: 'OG Kush',
    type: 'Indoor',
    time: '420 week',
    humidity: 19,
    fertilizer: 86,
    watering: 36,
    watertank: 4,
    light: 2,
    temperature: 0,
  },
];

export default plants;
